### ISSUE TITLE
Proposal on IsLoggedIn internals

### ISSUE THREAD

**Issue by VladimirAndrianov96** [Superciety/pwa-core-library#4]
Hey!

After updating an old code branch to the newest version I had some issues with DeFi connector, when I chose the DeFi wallet connector and then closed the Maiar extension pop-up (not logging in, just click on "sign in" and then close the extension), the code failed as it created this local storage item
`wallet_user` : `{"providerId":"maiar_extension"}` while it had no address inside, so that `.getAddress()` function failed afterwards `Error: wallet: user needs to login before`. 

This might be not the case with the recent code in general, but my workaround was to check the presence of the other keys as well like `address` in values `{"providerId":"maiar_extension","address":"red..."}`, I think the function can be a little extended here https://github.com/Superciety/pwa-core-library/blob/60dcd37647022537abc9d9bde7502312ae801ffb/src/services/wallet.ts#L152
to also look for the fields in local storage data

**Comment by michavie** [comment]
a little bit late, but thanks for reporting this! 🙏

it's fixed now in v0.18.2
